import { Asset, AssetType } from '@lib/models/asset.model'

export const getFeaturedAssets = async (): Promise<{
  featured: Asset[]
  trending: Asset[]
}> => {
  'use server'
  return {
    featured: [
      {
        id: '1',
        name: 'Asset 1',
        description: 'Short description of the item goes nicely here.',
        usageCount: 2845,
        tags: ['comms', 'coverage', 'stakeholders'],
        modified: '2024-06-27',
        type: AssetType.KPI,
        isFeatured: true,
        isTrending: true,
      },
      {
        id: '2',
        name: 'Asset 2',
        tags: ['comms', 'coverage', 'stakeholders'],
        description: 'Short description of the item goes nicely here.',
        usageCount: 2845,
        type: AssetType.Layout,
        isFeatured: true,
        isTrending: false,
      },
      {
        id: '3',
        name: 'Asset 3',
        tags: ['comms', 'coverage', 'stakeholders'],
        description: 'Short description of the item goes nicely here.',
        usageCount: 2845,
        type: AssetType.Storyboard,
        isFeatured: true,
        isTrending: false,
      },
      {
        id: '4',
        name: 'Asset 4',
        tags: ['comms', 'coverage', 'stakeholders'],
        description: 'Short description of the item goes nicely here.',
        usageCount: 2845,
        type: AssetType.DataViz,
        isFeatured: true,
        isTrending: true,
      },
    ],
    trending: [
      {
        id: '5',
        name: 'Asset 5',
        tags: ['comms', 'coverage', 'stakeholders'],
        description: 'Short description of the item goes nicely here.',
        usageCount: 2845,
        type: AssetType.KPI,
        isTrending: true,
        isFeatured: false,
      },
      {
        id: '6',
        name: 'Asset 6',
        tags: ['comms', 'coverage', 'stakeholders'],
        description: 'Short description of the item goes nicely here.',
        usageCount: 2845,
        modified: '2024-06-27',
        type: AssetType.Layout,
        isTrending: true,
        isFeatured: false,
      },
      {
        id: '7',
        name: 'Asset 7',
        tags: ['comms', 'coverage', 'stakeholders'],
        description: 'Short description of the item goes nicely here.',
        usageCount: 2845,
        modified: '2024-06-27',
        type: AssetType.DataViz,
        isTrending: true,
        isFeatured: false,
      },
      {
        id: '8',
        name: 'Asset 8',
        tags: ['comms', 'coverage', 'stakeholders'],
        description: 'Short description of the item goes nicely here.',
        usageCount: 2845,
        type: AssetType.Layout,
        isTrending: true,
        isFeatured: false,
      },
    ],
  }
}
export const getAssetsByType = async (type: AssetType): Promise<Asset[]> => {
  'use server'
  return [
    {
      id: '1',
      name: 'Asset 1',
      tags: ['comms', 'coverage', 'stakeholders'],
      type,
      description: 'Short description of the item goes nicely here.',
      usageCount: 2845,
      modified: '2024-06-27',
      isTrending: false,
      isFeatured: false,
    },
    {
      id: '2',
      name: 'Asset 2',
      tags: ['comms', 'coverage', 'stakeholders'],
      type,
      description: 'Short description of the item goes nicely here.',
      usageCount: 2845,
      modified: '2024-06-27',
      isTrending: false,
      isFeatured: false,
    },
    {
      id: '3',
      name: 'Asset 3',
      tags: ['comms', 'coverage', 'stakeholders'],
      type,
      description: 'Short description of the item goes nicely here.',
      usageCount: 2845,
      isTrending: false,
      isFeatured: false,
    },
    {
      id: '4',
      name: 'Asset 4',
      tags: ['comms', 'coverage', 'stakeholders'],
      type,
      description: 'Short description of the item goes nicely here.',
      usageCount: 2845,
      modified: '2024-06-27',
      isTrending: false,
      isFeatured: false,
    },
    {
      id: '5',
      name: 'Asset 5',
      tags: ['comms', 'coverage', 'stakeholders'],
      type,
      description: 'Short description of the item goes nicely here.',
      usageCount: 2845,
      modified: '2024-06-27',
      isTrending: false,
      isFeatured: false,
    },
    {
      id: '6',
      name: 'Asset 6',
      tags: ['comms', 'coverage', 'stakeholders'],
      type,
      description: 'Short description of the item goes nicely here.',
      usageCount: 2845,
      modified: '2024-06-27',
      isTrending: false,
      isFeatured: false,
    },
    {
      id: '7',
      name: 'Asset 7',
      tags: ['comms', 'coverage', 'stakeholders'],
      type,
      description: 'Short description of the item goes nicely here.',
      usageCount: 2845,
      isTrending: false,
      isFeatured: false,
    },
    {
      id: '8',
      name: 'Asset 8',
      tags: ['comms', 'coverage', 'stakeholders'],
      type,
      description: 'Short description of the item goes nicely here.',
      usageCount: 2845,
      modified: '2024-06-27',
      isTrending: false,
      isFeatured: false,
    },
  ]
}
